# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legotestquestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typecondition', models.IntegerField(choices=[(0, 'random'), (1, 'choose')], default=2)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legotestquestion.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legotestquestion.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('pull', models.IntegerField(choices=[(0, 'Basic'), (1, 'Bank')], default=0)),
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('typequestion', models.IntegerField(blank=True, choices=[(0, 'Question'), (1, 'Fill Description'), (2, 'Information'), (3, 'Match')], null=True)),
                ('full_score', models.IntegerField(default=0)),
                ('pass_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('category', models.IntegerField(blank=True, choices=[(0, 'AIS Products & Services'), (1, 'Handset & Device & Gadget'), (2, 'IT Development'), (3, 'Language Center'), (4, 'Customer Services'), (5, 'Corporate Culture'), (6, 'Leadership Management'), (7, 'Business Acumen'), (8, 'Compliance & Regulation'), (9, 'Ethics & Policy'), (10, 'Personal Development'), (11, 'Innovations'), (12, 'Office Productivity')], null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('provider', models.IntegerField(blank=True, choices=[(0, 'AIS Center'), (1, 'AIS Academy'), (2, 'CSM (Service)'), (3, 'CMD (TWZ)'), (4, 'ACC (Call Center)'), (5, 'TKM (Technical)')], null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('max_submit', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
                ('limit_day', models.IntegerField(blank=True, null=True)),
                ('limit_hour', models.IntegerField(blank=True, null=True)),
                ('limit_min', models.IntegerField(blank=True, null=True)),
                ('expired', models.IntegerField(blank=True, null=True)),
                ('expired_day', models.IntegerField(blank=True, null=True)),
                ('expired_hour', models.IntegerField(blank=True, null=True)),
                ('expired_min', models.IntegerField(blank=True, null=True)),
                ('descripe', models.TextField(blank=True, null=True)),
                ('is_display', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='legotest.Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='sectionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legotest.Section'),
        ),
        migrations.AddField(
            model_name='condition',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legotest.Section'),
        ),
    ]
