# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('pull', models.IntegerField(choices=[(0, 'Basic'), (1, 'Bank')])),
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('full_score', models.IntegerField(default=0)),
                ('pass_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
                ('typetest', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('provider', models.CharField(max_length=50)),
                ('condition', models.TextField()),
                ('max_submit', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('expired', models.DateTimeField(null=True)),
                ('descripe', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='legotest.Test'),
        ),
    ]
