# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionNum', models.AutoField(primary_key=True, serialize=False)),
                ('typequestion', models.CharField(max_length=50)),
                ('fullscore', models.IntegerField(default=0)),
                ('pass_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Img_name', models.ImageField(upload_to='image/')),
                ('typetest', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('provider', models.CharField(max_length=50)),
                ('condition', models.TextField()),
                ('max_submit', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('expired', models.DateTimeField(null=True)),
                ('descripe', models.TextField()),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legotest.Section')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='sectionNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legotest.Section'),
        ),
    ]
