# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='pass_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legotest.Test'),
        ),
    ]
