# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='expired_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='expired_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='expired_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='limit_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='limit_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='limit_min',
            field=models.IntegerField(null=True),
        ),
    ]
