# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='legotestquestion.Question'),
        ),
    ]
