# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0002_auto_20170620_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='sectionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='legotest.Section'),
        ),
    ]
