# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0003_auto_20170615_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='expired',
            field=models.IntegerField(null=True),
        ),
    ]
