# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0003_auto_20170621_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='expired_day',
        ),
        migrations.RemoveField(
            model_name='test',
            name='expired_hour',
        ),
        migrations.RemoveField(
            model_name='test',
            name='expired_min',
        ),
        migrations.RemoveField(
            model_name='test',
            name='limit_day',
        ),
        migrations.RemoveField(
            model_name='test',
            name='limit_hour',
        ),
        migrations.RemoveField(
            model_name='test',
            name='limit_min',
        ),
        migrations.AddField(
            model_name='test',
            name='expired_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='limit_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
