# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0004_auto_20170621_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='numquestion',
            field=models.IntegerField(default=0),
        ),
    ]
