# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0004_auto_20170620_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='legotest.Test'),
        ),
    ]
