# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0005_auto_20170616_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legotest.Question'),
        ),
    ]
