# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0006_auto_20170616_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='Question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legotest.Question'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legotest.Section'),
        ),
    ]
