# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0008_auto_20170616_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
