# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0009_test_is_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='typetest',
        ),
        migrations.AddField(
            model_name='section',
            name='typequestion',
            field=models.IntegerField(choices=[(0, 'Question'), (1, 'Fill Description'), (2, 'Information'), (3, 'Match')], default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'AIS Products & Services'), (1, 'Handset & Device & Gadget'), (2, 'IT Development'), (3, 'Language Center'), (4, 'Customer Services'), (5, 'Corporate Culture'), (6, 'Leadership Management'), (7, 'Business Acumen'), (8, 'Compliance & Regulation'), (9, 'Ethics & Policy'), (10, 'Personal Development'), (11, 'Innovations'), (12, 'Office Productivity')], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='descripe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='expired_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='expired_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='expired_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='limit_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='limit_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='limit_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='provider',
            field=models.IntegerField(blank=True, choices=[(0, 'AIS Center'), (1, 'AIS Academy'), (2, 'CSM (Service)'), (3, 'CMD (TWZ)'), (4, 'ACC (Call Center)'), (5, 'TKM (Technical)')], null=True),
        ),
    ]
