# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0010_auto_20170617_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='typecondition',
            field=models.IntegerField(choices=[(0, 'random'), (1, 'choose')], default=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='typequestion',
            field=models.IntegerField(blank=True, choices=[(0, 'Question'), (1, 'Fill Description'), (2, 'Information'), (3, 'Match')], null=True),
        ),
    ]
