# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legotest', '0011_auto_20170617_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='expired',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
