# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legocourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorm',
            fields=[
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='legocourse.Material')),
                ('image', models.ImageField(upload_to='scorm/%Y/%m/')),
            ],
        ),
    ]
