# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legoscorm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorm',
            name='id',
        ),
        migrations.AlterField(
            model_name='scorm',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='legocourse.Material'),
        ),
    ]
