# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legocourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='document/%Y/%m/')),
                ('document', models.FileField(upload_to='document/%Y/%m/')),
                ('lego_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legocourse.Material')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fileupload/%Y/%m/')),
                ('file', models.FileField(upload_to='fileupload/%Y/%m/')),
                ('lego_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legocourse.Material')),
            ],
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weblink/%Y/%m/')),
                ('data', models.URLField(max_length=256)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legocourse.Material')),
            ],
        ),
    ]
