# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legomaterial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='lego_material',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='lego_material',
            new_name='material',
        ),
    ]
