# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='course/%Y/%m/')),
                ('overview', models.TextField(max_length=250, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('is_display', models.BooleanField(default=True)),
                ('term_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(4, 'Audio'), (0, 'Video'), (1, 'WebLink'), (2, 'Document'), (5, 'Scorm'), (3, 'Test')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_name', models.CharField(max_length=200)),
                ('sort', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legocourse.Course')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legocourse.Section'),
        ),
    ]
