# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legocourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.IntegerField(choices=[(0, 'Video'), (1, 'WebLink'), (2, 'Document'), (3, 'Test'), (4, 'Audio'), (5, 'Scorm')], default=0),
        ),
    ]
