# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legocourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
