# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legocourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='types',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Web Link'), (3, 'Test'), (5, 'Scorm'), (2, 'Document'), (0, 'Video'), (4, 'Audio'), (6, 'File Upload')], default=0),
        ),
    ]
