# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legocourse', '0002_auto_20170622_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='types',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Test'), (6, 'File Upload'), (2, 'Document'), (5, 'Scorm'), (4, 'Audio'), (1, 'Web Link'), (0, 'Video')], default=0),
        ),
    ]
