# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legocourse', '0002_auto_20170613_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.IntegerField(choices=[(0, 'Video'), (1, 'WebLink'), (2, 'Document'), (3, 'Test'), (4, 'Audio'), (5, 'Scorm'), (6, 'FileUpload')], default=0),
        ),
    ]
