# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legocourse', '0003_remove_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='sort',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
