# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legotestquestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legotestquestion.Bank'),
        ),
    ]
