# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legotest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoresection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_section', models.IntegerField()),
                ('sectionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legotest.Section')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legotest.Test')),
            ],
        ),
    ]
