# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legocourse', '0002_auto_20170613_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weblink/%Y/%m/')),
                ('duration', models.DurationField()),
                ('status', models.IntegerField()),
                ('type', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legocourse.Material')),
            ],
        ),
    ]
